<?php
$quote = $this->getQuote();
$quoteId = $quote->getId();
// print_r($quoteId);
$item = $this->getItem();
$productId = Mage::getModel('sales/quote_item')->getProductId();
?>
<h1>Cart</h1>
<?php foreach ($item as $item):
 /*    echo "<pre>";
    print_r($item);
    print_r(get_class_methods($item));

    die(); */
    ?>

    <?php
    $product = Mage::getModel('catalog/product')->getCollection()
        ->addFieldToFilter('product_id', $item->getProductId())->getData();
    $itemId = $item->getId();
    // echo $itemId;
    ?>
    <?php foreach ($product as $product): ?>
        <div class="product-view" style="box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-3">
                        <!-- Image and Quantity Box -->
                        <div class="image-quantity-box">
                            <?php
                            $imageLink = $product->getImageLink();
                            if (!empty ($imageLink)) {
                                echo '<img src="' . Mage::getBaseUrl() . 'media/product/' . $imageLink . '" alt="Product Image" style="max-width: 100px;">';
                            } ?>
                            <div class="quantity-input">
                                <form action="<?php echo $this->getUrl('sales/quote/updateQuantity') ?>" method="post">
                                    <input type="hidden" name="update[item_id]" value="<?php echo $itemId ?>">
                                    <input type="hidden" name="update[quote_id]" value="<?php echo $quoteId ?>">
                                    <p><strong> </strong></p>
                                    <input type="number" class="form-control" name="update[qty]" id="qty" style="width: 60px;"
                                        value="<?php echo $item->getQty(); ?>">
                                    <input type="submit" class="btn btn-success" value="Update" name="submit">
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <!-- Details Box -->
                        <div class="details-box">
                            <h3>
                                <?php echo $product->getName(); ?>
                            </h3>
                            <p><strong>Description:</strong>
                                <?php echo $product->getDescription(); ?>
                            </p>
                            <p><strong>Name:</strong>
                                <?php echo $product->getName(); ?>
                            </p>
                            <p><strong>Price:</strong>
                                <?php echo $product->getPrice(); ?>
                            </p>
                            <p><strong>Total:</strong>
                                <?php echo $item->getRowTotal(); ?>
                            </p>
                            <!-- Remove Button -->
                            <form action="<?php echo $this->getUrl("sales/quote/remove") ?>" method="POST">
                                <input type="hidden" name="remove[item_id]" value="<?php echo $itemId ?>">
                                <input type="hidden" name="remove[quote_id]" value="<?php echo $quoteId ?>">
                                <!-- <button type="submit" class="btn btn-danger">Remove</button> -->
                                <input type="submit" class="btn btn-danger" value="Remove" name="submit">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
<?php endforeach; ?>

<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-12 text-center">

            <p><strong>Grand Total:</strong>
                <?php echo $quote->getGrandTotal(); ?>
            </p>
        </div>
    </div>
</div>
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-12 text-center">
            <form action="<?php echo $this->getUrl("sales/quote/checkout") ?>" method="POST">
                <button type="submit" class="btn btn-success">Checkout</button>
            </form>
        </div>
    </div>
</div>