<h1>Login form</h1>
<form id="customer-form" action="<?php echo $this->getUrl("customer/account/login") ?>" method="post">
<table>
    <tr>
        <td>
            Email
        </td>
        <td>
            <input type="email" placeholder="email" name="ldata[customer_email]" value="">
        </td>
    </tr>

    <tr>
        <td>
            Password
        </td>
        <td>
            <input type="password" placeholder="password" name="ldata[password]" value="">
        </td>
    </tr>
    <tr>
            <td>
                <input type="button" onclick="loginAction(this)" value="Submit" name="submit">
                
            </td>
        </tr>
</table>
<div id="message"></div>
</form>
<script type="text/javascript">
	function loginAction(btn) {
		//console.log($('#customer-form'));
		var form = $($('#customer-form'));
		console.log(form.serialize());
		$.ajax({
			url: form.action,
			type:'POST',
			// contentType: "application/json",
			data: form.serialize()	
		}).done(function(response) {
			var output = JSON.parse(response);
			// alert(response)
			alert(output.type)
			// $('#message')[0].innerHTML = output.message;
			// alert(output.message)
			// $( this ).addClass( "done" );
			// // $( this ).addClass( "done" );
            if(output.type=="success"){
				alert(output.message);
				window.location.href="<?php echo $this->getUrl('customer/account/dashboard');?>";
			}
			else{
				alert(output.message);
			}
			// $('#message')[0].innerHTML = output.message;
			// alert(output.message)
			// $( this ).addClass( "done" );
			// $( this ).addClass( "done" );
	
		});
	}
</script>
<!-- 
    form id="login form"
    input ttpe button
    submit button onclick "loginaction"
    <script type
    function loginaction(btn){
        console.log($(login form)) //len 1
        var form=$($(login form[0]) //
        console.log(form[0].action);
        console.log(form[0].serialize());



$.ajax({
  url: form.acion,
  type:'Post'
  content type
  context: form.serialize()
}).done(function() {
  $( this ).addClass( "done" );
});
    }

    tohtml
    obstart
    obclean
    catalog/product/view
    catalog/product/listsa
 -->