<!-- Footer -->
<footer class="text-center text-lg-start bg-dark text-light ">
  <!-- Section: Social media -->
  <section class="d-lg-flex justify-content-center justify-content-lg-between border-bottom">
    <!-- Left -->
    <div class="d-none d-lg-block text-center">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
                    <h6 class="text-uppercase font-weight-bold">Follow us</h6>

                    <!-- Facebook -->
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #FFCAD4"
                        href="https://www.facebook.com/" role="button">
                        <img src="<?php echo Mage::getBaseUrl() . "skin/images/icon/facebook_logo.png" ?>" alt="">
                    </a>

                    <!-- Twitter -->
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #55acee"
                        href="https://twitter.com/login" role="button"><img
                            src="<?php echo Mage::getBaseUrl() . "skin/images/icon/twitter_logo.JPG" ?>" alt="">
                    </a>
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #FEFBF6"
                        href="https://www.google.com/" role="button"><img
                            src="<?php echo Mage::getBaseUrl() . "skin/images/icon/google.jpg" ?>" alt=""></a>

                    <!-- Instagram -->
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #9AD0C2"
                        href="https://www.instagram.com/accounts/login/" role="button"><img
                            src="<?php echo Mage::getBaseUrl() . "skin/images/icon/instagram_logo.PNG" ?>" alt="">

                        <!-- Linkedin -->
                        <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #B47B84"
                            href="https://www.linkedin.com/login" role="button"><img
                                src="<?php echo Mage::getBaseUrl() . "skin/images/icon/linkedin.png" ?>" alt=""></a>
                        <!-- Github -->
                        <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #000000"
                            href="https://github.com/login" role="button"><img
                                src="<?php echo Mage::getBaseUrl() . "skin/images/icon/github.png" ?>" alt=""></a>
            </div>
    <!-- Right -->
  </section>
<footer class="text-center text-lg-start bg-dark text-light ">
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->