<nav>
            <div class="search-bar">
                <input type="text" placeholder="Search here">
                <button type="button">Search</button>
            </div>
            <ul class="user-buttons">
                <li class="login-button"><a href="#">Login</a></li>
                <li class="order-button"><a href="#">Order</a></li>
                <li class="cart-button"><a href="#">Cart</a></li>
            </ul>
        </nav>