<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <?php $this->getChildHtml('head');?>
</head>
<body>
    ADMIN
    
    <div class="header"><?php $this->getChildHtml('header');?></div>
    <div class="content"><?php $this->getChildHtml('content');?></div>
    <div class="footer"><?php $this->getChildHtml('footer');?></div>

</body>
</html>
