<style>
  #carouselExampleControls .carousel-item img {
    height: 550px; /* Set a fixed height for the carousel items */
    object-fit: cover; /* Ensure the entire image is visible within the fixed height */
  }

    img {
    /* Additional styles for all images */
    max-width: 100%; /* Ensure images don't exceed their container width */
    height: auto; /* Maintain the aspect ratio */
  
  }
</style>

<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100 " src="<?php echo Mage::getBaseUrl().'media/banner/banner10.jpg'?>" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src="<?php echo Mage::getBaseUrl().'media/banner/banner9.jpg'?>" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100 " src="<?php echo Mage::getBaseUrl().'media/banner/banner8.jpg'?>" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
