<h1>list</h1>
<?php
print_r($this);
$product=Mage::getModel("catalog/product")->getCollection();
?>
<!-- <div class="listTable"> -->
<div class="listTable">
<table >
    <tr>
        <th>Product Id</th>
        <th>SKU</th>
        <th>Name</th>
        <th>Color</th>
        <th>Size</th>
        <th>Description</th>
        <th>Image_Link</th>
        <th>Link</th>
        <th>Category ID</th>
        <th>Price</th>
        <th>Manufacturer Cost</th>
        <th>Shipping Cost</th>
        <th>Total Cost</th>
        <th>Margin Percentage</th>
        <th>Min Price</th>
        <th>Status</th>
        <th>View</th>
       
    </tr>
    <?php
    foreach($product->getData() as $product):?>
    <tr>
        <td>
            <?php print_r($product->getId()); ?>
        </td>
        <td>
                    <?php print_r($product->getSku()); ?>
                </td>
                <td>
                    <?php print_r($product->getName()); ?>
                </td>
                <td>
                    <?php print_r($product->getColor()); ?>
                </td>
                <td>
                    <?php print_r($product->getSize()); ?>
                </td>
                <td>
                    <?php print_r($product->getDescription()); ?>
                </td>
                <td>
                    <?php print_r($product->getImage_Link()); ?>
                </td>
                <td>
                    <?php print_r($product->getLink()); ?>
                </td>
                <td>
                    <?php print_r($product->getCategoryId()); ?>
                </td>


                <td>
                    <?php print_r($product->getPrice()); ?>
                </td>
                <td>
                    <?php print_r($product->getMfrCost()); ?>
                </td>

                <td>
                    <?php print_r($product->getShippingCost()); ?>
                </td>
                <td>
                    <?php print_r($product->getTotalCost()); ?>
                </td>
                <td>
                    <?php print_r($product->getMarginPercentage()); ?>
                </td>
                <td>
                    <?php print_r($product->getMin_Price()); ?>
                </td>
                <td>
                    <?php print_r($product->getStatus()); ?>
                </td>
                <td>
                    <a
                        href="http://localhost/cybercom_practice/NewMvc/catalog/product/view?id=<?php print_r($product->getId()) ?>">View</a>
                </td>
               
    </tr>
    <?php endforeach;?>

</table>
</div>