<?php
$product_model=$this->getProduct();
// print_r($product_model->getname());
?>
    <form action="<?php echo $this->getUrl("admin/catalog_product/save")?>" method="post">
        <table class="formTable">
            <tr>
                <td>
                  
                </td>
                <td>
                    <input type="hidden"  name="pdata[product_id]" value="<?php echo $product_model->getId();?>">
                </td>
            </tr>
            <tr>
                <td>
                    SKU:
                </td>
                <td>
                    <input type="text" placeholder="SKU" name="pdata[sku]" value="<?php echo $product_model->getSku();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Name:
                </td>
                <td>
                    <input type="text" placeholder="Name"  name="pdata[name]" value="<?php echo $product_model->getName();?>">
                </td>          
            </tr>
            <tr>
                <td>
                    Color:
                </td>
                <td>
                    <input type="text" placeholder="Color" name="pdata[color]" value="<?php echo $product_model->getColor();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Size:
                </td>
                <td>
                    <input type="text" placeholder="Size" name="pdata[size]" value="<?php echo $product_model->getSize();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Description:
                </td>
                <td>
                    <input type="text" placeholder="Description" name="pdata[description]" value="<?php echo $product_model->getDescription();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Image_Link:
                </td>
                <td>
                    <input type="text" name="pdata[image_link]" value="<?php echo $product_model->getImageLink();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Link:
                </td>
                <td>
                    <input type="text" name="pdata[link]" value="<?php echo $product_model->getLink();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Category ID:
                </td>
                <td>
                    <input type="number" placeholder="Category ID" name="pdata[category_id]" value="<?php echo $product_model->getCategoryId();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Price:
                </td>
                <td>
                    <input type="number" placeholder="Price" name="pdata[price]" value="<?php echo $product_model->getPrice();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Manufacturer Cost:
                </td>
                <td>
                    <input type="number" placeholder="Manufacturer Cost" name="pdata[mfr_cost]" value="<?php echo $product_model->getMfrCost();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Shipping Cost:
                </td>
                <td>
                    <input type="number" placeholder="Shipping Cost" name="pdata[shipping_cost]" value="<?php echo $product_model->getShippingCost();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Total Cost:
                </td>
                <td>
                    <input type="number" placeholder="Total Cost" name="pdata[total_cost]" value="<?php echo $product_model->getTotalCost();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Margin Percentage:
                </td>
                <td>
                    <input type="number" placeholder="Margin Percentage" name="pdata[margin_percentage]" value="<?php echo $product_model->getMarginPercentage();?>">
                </td
            </tr>
            <tr>
                <td>
                    Min Price:
                </td>
                <td>
                    <input type="number" placeholder="Min Price" name="pdata[min_price]" value="<?php echo $product_model->getMinPrice();?>">
                </td>
            </tr>
            <tr>
                <td>
                    Status:
                </td>
                <td>
                    <select name="pdata[status]">
                        <option value="enabled">Enabled</option>
                        <option value="disabled">Disabled</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Submit" name="submit">
                </td>
            </tr>
        </table>
    </form>

