<?php
echo Mage::getSingleton('core/session')->remove('customer_id');
$product_model = $this->getProduct();
// print_r($product_model->getname());
?>
<div class="container">
<form id="form" action="<?php echo $this->getUrl("admin/catalog_product/save") ?>" method="post">
    <table class="formTable">
        <tr>
            <td>

            </td>
            <td>
                <input type="hidden" name="pdata[product_id]" value="<?php echo $product_model->getId(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                SKU:
            </td>
            <td>
                <input type="text" placeholder="SKU" name="pdata[sku]" value="<?php echo $product_model->getSku(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Name:
            </td>
            <td>
                <input type="text" placeholder="Name" name="pdata[name]"
                    value="<?php echo $product_model->getName(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Color:
            </td>
            <td>
                <input type="text" placeholder="Color" name="pdata[color]"
                    value="<?php echo $product_model->getColor(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Size:
            </td>
            <td>
                <input type="text" placeholder="Size" name="pdata[size]"
                    value="<?php echo $product_model->getSize(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Description:
            </td>
            <td>
                <input type="text" placeholder="Description" name="pdata[description]"
                    value="<?php echo $product_model->getDescription(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Image_Link:
            </td>
            <td>
                <input type="text" placeholder="Image Link" name="pdata[image_link]"
                    value="<?php echo $product_model->getImageLink(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Link:
            </td>
            <td>
                <input type="text" placeholder="Link" name="pdata[link]"
                    value="<?php echo $product_model->getLink(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Category:
            </td>
            <td>
                <select name="pdata[category_id]" id="category_id">

                    <option value="1" <?php echo ($product_model->getCategoryId()) == 'Bar & Game Room' ? 'selected' : ''; ?>>Bar & Game Room </option>
                    <option value="2" <?php echo ($product_model->getCategoryId()) == 'Bedroom' ? 'selected' : ''; ?>>
                        Bedroom</option>
                    <option value="3" <?php echo ($product_model->getCategoryId()) == 'Decor' ? 'selected' : ''; ?>>Decor
                    </option>
                    <option value="4" <?php echo ($product_model->getCategoryId()) == 'Dining & Kitchen' ? 'selected' : ''; ?>>Dining & Kitchen</option>
                    <option value="5" <?php echo ($product_model->getCategoryId()) == 'Lighting' ? 'selected' : ''; ?>>
                        Lighting</option>
                    <option value="6" <?php echo ($product_model->getCategoryId()) == 'Living Room' ? 'selected' : ''; ?>>
                        Living Room</option>
                    <option value="7" <?php echo ($product_model->getCategoryId()) == 'Mattresses' ? 'selected' : ''; ?>>
                        Mattresses</option>
                    <option value="8" <?php echo ($product_model->getCategoryId()) == 'Office' ? 'selected' : ''; ?>>
                        Office</option>
                    <option value="9" <?php echo ($product_model->getCategoryId()) == 'Outdoor' ? 'selected' : ''; ?>>
                        Outdoor</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                Price:
            </td>
            <td>
                <input type="text" placeholder="Price" name="pdata[price]"
                    value="<?php echo $product_model->getPrice(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Manufacturer Cost:
            </td>
            <td>
                <input type="number" placeholder="Manufacturer Cost" name="pdata[mfr_cost]"
                    value="<?php echo $product_model->getMfrCost(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Shipping Cost:
            </td>
            <td>
                <input type="number" placeholder="Shipping Cost" name="pdata[shipping_cost]"
                    value="<?php echo $product_model->getShippingCost(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Total Cost:
            </td>
            <td>
                <input type="number" placeholder="Total Cost" name="pdata[total_cost]"
                    value="<?php echo $product_model->getTotalCost(); ?>">
            </td>
        </tr>

        <td>
            Margin Percentage:
        </td>
        <td>
            <input type="number" placeholder="Margin Percentage" name="pdata[margin_percentage]"
                value="<?php echo $product_model->getMarginPercentage(); ?>">
        </td>
        <tr>
            <td>
                Min Price:
            </td>
            <td>
                <input type="number" placeholder="Minimum Price" name="pdata[min_price]"
                    value="<?php echo $product_model->getMinPrice(); ?>">
            </td>
        </tr>
        <tr>
            <td>
                Status:
            </td>
            <td>
                <select name="pdata[status]">
                    <option value=" 1" <?php echo ($product_model->getStatus() == 1) ? 'selected' : ''; ?>>Enabled
                    </option>
                    <option value="0" <?php echo ($product_model->getStatus() == 0) ? 'selected' : ''; ?>>Disabled
                    </option>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Submit" name="submit">
            </td>
        </tr>
    </table>
</form>
</div>