<h1>Chatting</h1>

<?php
$chatModel = Mage::getModel('chatting/chatting');
$lastUser = $chatModel->getLastUser();

if ($lastUser) {
    $last = $lastUser->getFromUser();
    $lastToUser = $lastUser->getToUser();
} else {
    $last = $lastToUser = '';
}

?>
<form action=<?php echo $this->getUrl("chatting/user/save") ?> method="post">
    <table class="formTable">
        <tr>

            <td>
                <input type="hidden" name="chatting_data[id]" value="">
            </td>
        </tr>
   

        <tr>
            <td>
                From USER
            </td>
            <td>
                <input type="text" name="chatting_data[from_user]" value="<?php echo $lastToUser?>">
            </td>
        </tr>
        <tr>

            <td>
                <input type="hidden" name="chatting_data[to_user]" value="<?php echo $last ?>">
            </td>
        </tr>


        <tr>
            <td>
                Message
            </td>
            <td>
                <input type="text" name="chatting_data[message]" value="">
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Submit" name="submit">
            </td>
        </tr>
    </table>


</form>